meta_product_name: "Clique Sorriso"
meta_title: "Clique Sorriso - Seu Gerenciador de Consultas Odontol칩gicas"
meta_description: "Gerenciador de consultas que possibilita aos pacientes marcar hor치rios, fazer consulta online e localizar laborat칩rios mais pr칩ximos"
meta_image: "clique_sorriso_logo.png" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"